name: "Install GithubRelease action"
description: " Installs Github release"
inputs:
  repo:
    description: "GitHub repo where binary is located"
    required: true
  tag:
    description: "tag containing binary to install"
    default: latest
    required: true
  token:
    description: "access token"
    required: true
branding:
  icon: "archive"
  color: "green"
runs:
  using: "node20"
  main: "dist/index.js"
